### ISSUE TITLE
some wrong about your code

### ISSUE THREAD

**Issue by lianxiszp** [rak13/2048-Assembly#1]
## background

I'm student learning assembly

however, my teacher doesn't teach about that,so i need to search some code to through my class.

## problem

my environment is : 
- masm 5.0
- dosbox 
- operating system windows 10

when i compile your asm file:`masm Final 2048.asm`, there is some wrong.
can you adjust it? thank you.

**Comment by rak13** [comment]
@lianxiszp 
Please point out the error to me.
Try running/compiling the program using the emu8086 provided in the repo.

**Comment by muyuuuu** [comment]
Ok, here is:

ASM file from : https://github.com/rak13/2048-Assembly/blob/master/2048%20Final.asm

with emu8086 compiling, error:
![image](https://user-images.githubusercontent.com/43681138/54275522-cce5d900-45c5-11e9-8cc4-b3590a973df4.png)

environment error? or code error?

thank u

**Comment by muyuuuu** [comment]
but what amazing is that your `.exe` file can run correctly in dosbox

**Comment by rak13** [comment]
Well... I can still compile and run the project without any issues.
![run](https://user-images.githubusercontent.com/14104929/54287985-a59d0500-45e1-11e9-91c1-e31849e66e1e.png)
All I did was install the `emu8086_4.08` from this repo, opened the file `2048 Final.asm` and hit the `emulate` button. Then saved the `.exe` and run it Dosbox.

**Comment by muyuuuu** [comment]
That's amazing, maybe `emu8086 version`  led the problem?
I'am in China, it's midnight now, i'll go sleep.
I will change my emu version and run code again tomorrow, good night.

**Comment by muyuuuu** [comment]
But, about your other environment version ?

Such as 
- masm version
- dosbox version
- operating system version

maybe...the issue from that.

**Comment by rak13** [comment]
I am running windows 10, `DOSBox0.74-win32-installer.exe` provided in this repo.
Dos box version won't affect the compiling.

**Comment by muyuuuu** [comment]
What incomprehensible is, there are the same error when i hit the emulate button: 

![image](https://user-images.githubusercontent.com/43681138/54331524-5c869880-4655-11e9-9ed3-1699e4057c14.png)

I don't think reason is he string  `?`

I will consult my teacher about that, after solving the issue, I will tell you.

In addition ,your avatar is so cool.

**Comment by muyuuuu** [comment]
## problem 1  

Maybe supernatural event?

When I change your code by some suggestions which from search engine, then I can compile correct.

Modification：
- in lines 235, 240, 241, 242, change `?` to `'?'`

Then,  I could compile `.asm` file and generate an `.exe` file, can you explain it?

## problem 2

The game ends when it cannot move, not when all the placards have elements.

In your program, all the placards have elements the game will be over, but, all the placards have elements can also move continue, the game is not over yet.

**Comment by rak13** [comment]
Looks like you found a bug 

> all the placards have elements can also move to continue, the game is not over yet.

Could you create a merge request with the fix?

And,
About the compile error, I guess there's a difference in the  compiler versions that caused this issue.

**Comment by muyuuuu** [comment]
I can offer some ideas to solve that,  but I will not implement it with code for the time being.

Some ideas:
- First, writing a subfunction which we call the detection function,  executed when all the placards have elements.
- Then, the function of the subfunction implementation is: we user push buttons `→←↑↓`, if the elements in all the grids have not changed, the game could be over.

Can you understand me? My `Chinese-style` English may not be clearly expressed my meaning.

**Comment by rak13** [comment]
I have ideas to solve the problem! I coded the whole thing!
I am just not interested to fix this small issue.
If you fix it, then create a merge-request.
